//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package ascii


//go:noescape
func IsASCII(data string) bool

//go:noescape
func IndexBit(data string, mask byte) int

//go:noescape
func EqualFold(a string, b string) bool

//go:noescape
func index_fold_simd(a string, b string) int
