package asm

import (
	"strings"
	"testing"

	"github.com/mhr3/gocc/internal/config"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ARM64 Stack Pattern Tests
//
// These tests cover the different stack frame patterns generated by clang for ARM64.
// The gocc stack transform must handle all patterns correctly to avoid stack corruption.
//
// Key patterns:
// 1. Leaf function - no stack manipulation at all
// 2. Simple frame - just stp/ldp x29,x30 with pre/post-index
// 3. Callee-saved registers - saves x19-x28 in addition to x29,x30
// 4. Simple stack allocation - sub sp,sp,#N ... add sp,sp,#N (symmetric)
// 5. Complex frame pointer - uses mov x29,sp / mov sp,x29 for stack restore after alignment
//
// For Go's ABI0:
// - No callee-saved registers need to be preserved
// - Go manages stack frame via TEXT declaration
// - All SP-modifying instructions should be NOPed
// - Frame pointer save/restore should be NOPed

func TestArm64LeafFunction(t *testing.T) {
	// Pattern: Leaf function with no stack usage at all
	// Should pass through unchanged with LocalsSize = 0
	testFn := Function{
		Name: "leaf_func",
		Lines: []Line{
			{Assembly: "cbz	x1, .LBB0_4", Binary: wordToLineBinary(0xb4000021)},
			{Assembly: "add	x9, x0, x1", Binary: wordToLineBinary(0x8b010009)},
			{Assembly: "mov	x0, xzr", Binary: wordToLineBinary(0xaa1f03e0)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	modified := checkStackArm64(config.ARM64(), testFn)

	assert.Equal(t, 0, modified.LocalsSize, "leaf function should have LocalsSize=0")
	require.Len(t, modified.Lines, 4)
	// All instructions should pass through unchanged
	for i, line := range modified.Lines {
		if line.Assembly != "ret" {
			assert.NotEqual(t, "NOP", modified.Lines[i].Disassembled,
				"leaf function instructions should not be NOPed")
		}
	}
}

func TestArm64SimpleFramePointer(t *testing.T) {
	// Pattern: Simple frame with just x29,x30 save/restore (16 bytes)
	// This is the minimal non-leaf pattern
	testFn := Function{
		Name: "simple_frame",
		Lines: []Line{
			{Assembly: "stp	x29, x30, [sp, #-16]!", Binary: wordToLineBinary(0xa9bf7bfd)},
			{Assembly: "mov	x29, sp", Binary: wordToLineBinary(0x910003fd)},
			// function body
			{Assembly: "mov	w0, #1", Binary: wordToLineBinary(0x52800020)},
			{Assembly: "ldp	x29, x30, [sp], #16", Binary: wordToLineBinary(0xa8c17bfd)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	modified := checkStackArm64(config.ARM64(), testFn)

	assert.Equal(t, 0, modified.LocalsSize, "simple frame should have LocalsSize=0")
	require.Len(t, modified.Lines, 5)
	assert.Equal(t, "NOP", modified.Lines[0].Disassembled, "stp x29,x30 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[1].Disassembled, "mov x29,sp should be NOPed")
	assert.NotEqual(t, "NOP", modified.Lines[2].Disassembled, "function body should be kept")
	assert.Equal(t, "NOP", modified.Lines[3].Disassembled, "ldp x29,x30 should be NOPed")
	assert.Equal(t, "RET", modified.Lines[4].Disassembled)
}

func TestArm64CalleeSavedRegisters(t *testing.T) {
	// Pattern: Frame with callee-saved registers x19-x28
	// All callee-saved register operations should be NOPed for Go ABI0
	testFn := Function{
		Name: "callee_saved",
		Lines: []Line{
			{Assembly: "stp	x29, x30, [sp, #-48]!", Binary: wordToLineBinary(0xa9bd7bfd)},
			{Assembly: "stp	x22, x21, [sp, #16]", Binary: wordToLineBinary(0xa90157f6)},
			{Assembly: "stp	x20, x19, [sp, #32]", Binary: wordToLineBinary(0xa9024ff4)},
			{Assembly: "mov	x29, sp", Binary: wordToLineBinary(0x910003fd)},
			// function body
			{Assembly: "mov	w0, #1", Binary: wordToLineBinary(0x52800020)},
			// epilogue
			{Assembly: "ldp	x20, x19, [sp, #32]", Binary: wordToLineBinary(0xa9424ff4)},
			{Assembly: "ldp	x22, x21, [sp, #16]", Binary: wordToLineBinary(0xa94157f6)},
			{Assembly: "ldp	x29, x30, [sp], #48", Binary: wordToLineBinary(0xa8c37bfd)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	modified := checkStackArm64(config.ARM64(), testFn)

	assert.Equal(t, 0, modified.LocalsSize, "callee-saved only should have LocalsSize=0")
	require.Len(t, modified.Lines, 9)
	// All frame setup/teardown should be NOPed
	assert.Equal(t, "NOP", modified.Lines[0].Disassembled, "stp x29,x30 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[1].Disassembled, "stp x22,x21 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[2].Disassembled, "stp x20,x19 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[3].Disassembled, "mov x29,sp should be NOPed")
	assert.NotEqual(t, "NOP", modified.Lines[4].Disassembled, "function body should be kept")
	assert.Equal(t, "NOP", modified.Lines[5].Disassembled, "ldp x20,x19 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[6].Disassembled, "ldp x22,x21 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[7].Disassembled, "ldp x29,x30 should be NOPed")
	assert.Equal(t, "RET", modified.Lines[8].Disassembled)
}

func TestArm64SimpleStackAllocation(t *testing.T) {
	// Pattern: Simple stack allocation with symmetric sub/add (no -mstackrealign)
	// This pattern is generated by clang WITHOUT -mstackrealign
	//
	// Prologue: sub sp, sp, #160 then save registers at fixed offsets
	// Epilogue: restore registers then add sp, sp, #160
	//
	// This is simpler than the frame-pointer pattern because:
	// - No mov x29,sp / mov sp,x29 dance
	// - Stack restore is via symmetric add sp, not via frame pointer
	testFn := Function{
		Name: "simple_stack_alloc",
		Lines: []Line{
			// Prologue
			{Assembly: "sub	sp, sp, #160", Binary: wordToLineBinary(0xd10283ff)},
			{Assembly: "stp	x29, x30, [sp, #80]", Binary: wordToLineBinary(0xa9057bfd)},
			{Assembly: "stp	x26, x25, [sp, #96]", Binary: wordToLineBinary(0xa90667fa)},
			{Assembly: "stp	x24, x23, [sp, #112]", Binary: wordToLineBinary(0xa9075ff8)},
			{Assembly: "stp	x22, x21, [sp, #128]", Binary: wordToLineBinary(0xa90857f6)},
			{Assembly: "stp	x20, x19, [sp, #144]", Binary: wordToLineBinary(0xa9094ff4)},
			// Function body - uses stack for locals
			{Assembly: "str	x8, [sp, #8]", Binary: wordToLineBinary(0xf90007e8)},
			{Assembly: "ldr	x8, [sp, #8]", Binary: wordToLineBinary(0xf94007e8)},
			// Epilogue
			{Assembly: "ldp	x20, x19, [sp, #144]", Binary: wordToLineBinary(0xa9494ff4)},
			{Assembly: "ldp	x22, x21, [sp, #128]", Binary: wordToLineBinary(0xa94857f6)},
			{Assembly: "ldp	x24, x23, [sp, #112]", Binary: wordToLineBinary(0xa9475ff8)},
			{Assembly: "ldp	x26, x25, [sp, #96]", Binary: wordToLineBinary(0xa94667fa)},
			{Assembly: "ldp	x29, x30, [sp, #80]", Binary: wordToLineBinary(0xa9457bfd)},
			{Assembly: "add	sp, sp, #160", Binary: wordToLineBinary(0x910283ff)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	modified := checkStackArm64(config.ARM64(), testFn)

	t.Logf("LocalsSize: %d", modified.LocalsSize)
	for i, line := range modified.Lines {
		t.Logf("Line %d: asm=%q disasm=%q", i, line.Assembly, line.Disassembled)
	}

	// LocalsSize should account for the stack space used by locals (160 - callee saves)
	// The function uses [sp, #8] for locals, and callee saves are at offsets 80-160
	// So locals use 0-80 = 80 bytes
	assert.True(t, modified.LocalsSize > 0, "should have some LocalsSize for locals")

	require.Len(t, modified.Lines, 15)

	// All stack allocation/deallocation should be NOPed
	assert.Equal(t, "NOP", modified.Lines[0].Disassembled, "sub sp,sp,#160 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[1].Disassembled, "stp x29,x30 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[2].Disassembled, "stp x26,x25 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[3].Disassembled, "stp x24,x23 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[4].Disassembled, "stp x22,x21 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[5].Disassembled, "stp x20,x19 should be NOPed")

	// Function body stack accesses should be transformed (not NOPed)
	assert.NotEqual(t, "NOP", modified.Lines[6].Disassembled, "str x8,[sp] should be transformed, not NOPed")
	assert.NotEqual(t, "NOP", modified.Lines[7].Disassembled, "ldr x8,[sp] should be transformed, not NOPed")

	// Epilogue
	assert.Equal(t, "NOP", modified.Lines[8].Disassembled, "ldp x20,x19 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[9].Disassembled, "ldp x22,x21 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[10].Disassembled, "ldp x24,x23 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[11].Disassembled, "ldp x26,x25 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[12].Disassembled, "ldp x29,x30 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[13].Disassembled, "add sp,sp,#160 should be NOPed (symmetric with sub)")
	assert.Equal(t, "RET", modified.Lines[14].Disassembled)
}

func TestArm64ComplexFramePointer(t *testing.T) {
	// Pattern: Complex frame pointer pattern (with -mstackrealign or stack alignment)
	// This uses mov x29,sp to save SP, then mov sp,x29 to restore it
	//
	// This pattern is problematic because:
	// 1. Stack alignment via "and sp, x9, #..." makes the actual SP different from saved FP
	// 2. Restoration via "mov sp, x29" depends on x29 having been saved
	// 3. If we NOP the save but not the restore, we corrupt the stack
	//
	// The fix: Both mov x29,sp (save) and mov sp,x29 (restore) must be NOPed together
	testFn := Function{
		Name: "complex_frame_pointer",
		Lines: []Line{
			// Prologue with -mstackrealign pattern
			{Assembly: "stp	x29, x30, [sp, #-80]!", Binary: wordToLineBinary(0xa9bb7bfd)},
			{Assembly: "sub	x9, sp, #80", Binary: wordToLineBinary(0xd10143e9)},
			{Assembly: "stp	x26, x25, [sp, #16]", Binary: wordToLineBinary(0xa90167fa)},
			{Assembly: "stp	x24, x23, [sp, #32]", Binary: wordToLineBinary(0xa9025ff8)},
			{Assembly: "mov	x29, sp", Binary: wordToLineBinary(0x910003fd)}, // SAVE SP to FP
			{Assembly: "stp	x22, x21, [sp, #48]", Binary: wordToLineBinary(0xa90357f6)},
			{Assembly: "stp	x20, x19, [sp, #64]", Binary: wordToLineBinary(0xa9044ff4)},
			{Assembly: "and	sp, x9, #0xfffffffffffffff8", Binary: wordToLineBinary(0x927df13f)},
			// Function body
			{Assembly: "mov	w0, #1", Binary: wordToLineBinary(0x52800020)},
			// Epilogue
			{Assembly: "mov	sp, x29", Binary: wordToLineBinary(0x910003bf)}, // RESTORE SP from FP
			{Assembly: "ldp	x20, x19, [sp, #64]", Binary: wordToLineBinary(0xa9444ff4)},
			{Assembly: "ldp	x22, x21, [sp, #48]", Binary: wordToLineBinary(0xa94357f6)},
			{Assembly: "ldp	x24, x23, [sp, #32]", Binary: wordToLineBinary(0xa9425ff8)},
			{Assembly: "ldp	x26, x25, [sp, #16]", Binary: wordToLineBinary(0xa94167fa)},
			{Assembly: "ldp	x29, x30, [sp], #80", Binary: wordToLineBinary(0xa8c57bfd)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	modified := checkStackArm64(config.ARM64(), testFn)

	require.Len(t, modified.Lines, 16)

	// All prologue stack setup should be NOPed
	assert.Equal(t, "NOP", modified.Lines[0].Disassembled, "stp x29,x30 should be NOPed")
	assert.True(t, strings.HasPrefix(modified.Lines[1].Disassembled, "MOV"), "sub x9,sp should become MOV x9,sp")
	assert.Equal(t, "NOP", modified.Lines[2].Disassembled, "stp x26,x25 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[3].Disassembled, "stp x24,x23 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[4].Disassembled, "mov x29,sp (FP save) should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[5].Disassembled, "stp x22,x21 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[6].Disassembled, "stp x20,x19 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[7].Disassembled, "and sp,x9 (alignment) should be NOPed")

	// Function body should be preserved
	assert.NotEqual(t, "NOP", modified.Lines[8].Disassembled, "function body should be kept")

	// CRITICAL: Both FP save AND restore must be NOPed
	assert.Equal(t, "NOP", modified.Lines[9].Disassembled, "mov sp,x29 (FP restore) MUST be NOPed")

	// All epilogue callee-saved restores should be NOPed
	assert.Equal(t, "NOP", modified.Lines[10].Disassembled, "ldp x20,x19 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[11].Disassembled, "ldp x22,x21 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[12].Disassembled, "ldp x24,x23 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[13].Disassembled, "ldp x26,x25 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[14].Disassembled, "ldp x29,x30 should be NOPed")
	assert.Equal(t, "RET", modified.Lines[15].Disassembled)
}

func TestArm64FramePointerRestore(t *testing.T) {
	// Minimal test for the specific bug: mov sp,x29 must be NOPed if mov x29,sp is NOPed
	// This was the root cause of the "unexpected return pc" crash
	testFn := Function{
		Name: "fp_restore_test",
		Lines: []Line{
			{Assembly: "stp	x29, x30, [sp, #-16]!", Binary: wordToLineBinary(0xa9bf7bfd)},
			{Assembly: "mov	x29, sp", Binary: wordToLineBinary(0x910003fd)}, // FP save
			{Assembly: "and	sp, x9, #0xfffffffffffffff8", Binary: wordToLineBinary(0x927df13f)},
			{Assembly: "mov	sp, x29", Binary: wordToLineBinary(0x910003bf)}, // FP restore
			{Assembly: "ldp	x29, x30, [sp], #16", Binary: wordToLineBinary(0xa8c17bfd)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	modified := checkStackArm64(config.ARM64(), testFn)

	require.Len(t, modified.Lines, 6)
	assert.Equal(t, "NOP", modified.Lines[0].Disassembled, "stp should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[1].Disassembled, "mov x29,sp (save) should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[2].Disassembled, "and sp,x9 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[3].Disassembled, "mov sp,x29 (restore) MUST be NOPed")
	assert.Equal(t, "NOP", modified.Lines[4].Disassembled, "ldp should be NOPed")
	assert.Equal(t, "RET", modified.Lines[5].Disassembled)
}

func TestArm64SingleRegisterCalleeSaved(t *testing.T) {
	// Test single STR/LDR for callee-saved registers (not paired STP/LDP)
	testFn := Function{
		Name: "single_reg_save",
		Lines: []Line{
			{Assembly: "stp	x29, x30, [sp, #-32]!", Binary: wordToLineBinary(0xa9be7bfd)},
			{Assembly: "str	x19, [sp, #16]", Binary: wordToLineBinary(0xf9000bf3)},
			{Assembly: "str	x20, [sp, #24]", Binary: wordToLineBinary(0xf9000ff4)},
			// body
			{Assembly: "mov	w0, #1", Binary: wordToLineBinary(0x52800020)},
			// epilogue
			{Assembly: "ldr	x20, [sp, #24]", Binary: wordToLineBinary(0xf9400ff4)},
			{Assembly: "ldr	x19, [sp, #16]", Binary: wordToLineBinary(0xf9400bf3)},
			{Assembly: "ldp	x29, x30, [sp], #32", Binary: wordToLineBinary(0xa8c27bfd)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	modified := checkStackArm64(config.ARM64(), testFn)

	require.Len(t, modified.Lines, 8)
	assert.Equal(t, "NOP", modified.Lines[0].Disassembled, "stp x29,x30 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[1].Disassembled, "str x19 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[2].Disassembled, "str x20 should be NOPed")
	assert.NotEqual(t, "NOP", modified.Lines[3].Disassembled, "body should be kept")
	assert.Equal(t, "NOP", modified.Lines[4].Disassembled, "ldr x20 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[5].Disassembled, "ldr x19 should be NOPed")
	assert.Equal(t, "NOP", modified.Lines[6].Disassembled, "ldp x29,x30 should be NOPed")
	assert.Equal(t, "RET", modified.Lines[7].Disassembled)
}

func TestArm64RegisterPairOrdering(t *testing.T) {
	// Different compilers may emit callee-saved pairs in different orders
	// Both (x19,x20) and (x20,x19) orderings should be recognized
	testCases := []struct {
		name     string
		assembly string
		binary   uint32
	}{
		{"x19_x20", "stp	x19, x20, [sp, #16]", 0xa90153f3},
		{"x20_x19", "stp	x20, x19, [sp, #16]", 0xa9014ff4},
		{"x21_x22", "stp	x21, x22, [sp, #32]", 0xa9025bf5},
		{"x22_x21", "stp	x22, x21, [sp, #32]", 0xa90257f6},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			testFn := Function{
				Name: "pair_order_" + tc.name,
				Lines: []Line{
					{Assembly: "stp	x29, x30, [sp, #-32]!", Binary: wordToLineBinary(0xa9be7bfd)},
					{Assembly: tc.assembly, Binary: wordToLineBinary(tc.binary)},
					{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
				},
			}

			modified := checkStackArm64(config.ARM64(), testFn)

			require.Len(t, modified.Lines, 3)
			assert.Equal(t, "NOP", modified.Lines[0].Disassembled)
			assert.Equal(t, "NOP", modified.Lines[1].Disassembled, "%s should be NOPed", tc.name)
			assert.Equal(t, "RET", modified.Lines[2].Disassembled)
		})
	}
}

func TestArm64NonCalleeSavedRegisters(t *testing.T) {
	// STR/LDR to registers that are NOT callee-saved should be preserved
	// x0-x15 are scratch/argument registers
	testFn := Function{
		Name: "non_callee_saved",
		Lines: []Line{
			{Assembly: "stp	x29, x30, [sp, #-32]!", Binary: wordToLineBinary(0xa9be7bfd)},
			{Assembly: "str	x0, [sp, #16]", Binary: wordToLineBinary(0xf9000be0)},  // argument save
			{Assembly: "str	x8, [sp, #24]", Binary: wordToLineBinary(0xf9000fe8)},  // scratch save
			{Assembly: "ldr	x8, [sp, #24]", Binary: wordToLineBinary(0xf9400fe8)},
			{Assembly: "ldr	x0, [sp, #16]", Binary: wordToLineBinary(0xf9400be0)},
			{Assembly: "ldp	x29, x30, [sp], #32", Binary: wordToLineBinary(0xa8c27bfd)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	modified := checkStackArm64(config.ARM64(), testFn)

	require.Len(t, modified.Lines, 7)
	assert.Equal(t, "NOP", modified.Lines[0].Disassembled, "stp x29,x30 should be NOPed")
	// x0 and x8 are NOT callee-saved, so their str/ldr should be kept
	assert.NotEqual(t, "NOP", modified.Lines[1].Disassembled, "str x0 should be kept (not callee-saved)")
	assert.NotEqual(t, "NOP", modified.Lines[2].Disassembled, "str x8 should be kept (not callee-saved)")
	assert.NotEqual(t, "NOP", modified.Lines[3].Disassembled, "ldr x8 should be kept")
	assert.NotEqual(t, "NOP", modified.Lines[4].Disassembled, "ldr x0 should be kept")
	assert.Equal(t, "NOP", modified.Lines[5].Disassembled, "ldp x29,x30 should be NOPed")
	assert.Equal(t, "RET", modified.Lines[6].Disassembled)
}



func TestArm64DynamicStackAllocationPanics(t *testing.T) {
	// Pattern: Dynamic stack allocation with register operand (alloca/VLA)
	// This is impossible to handle because Go needs stack size at compile time.
	// The transform should panic with a clear error message.
	//
	// Example C code that generates this:
	//   void func(int n) { char buf[n]; ... }  // VLA
	//   void func(int n) { char *p = alloca(n); ... }  // alloca
	//
	// Clang generates: sub sp, sp, x8 (where x8 contains the dynamic size)

	testFn := Function{
		Name: "dynamic_alloc_func",
		Lines: []Line{
			// Prologue
			{Assembly: "sub\tsp, sp, #32", Binary: wordToLineBinary(0xd10083ff)},
			{Assembly: "stp\tx29, x30, [sp, #16]", Binary: wordToLineBinary(0xa9017bfd)},
			// Dynamic allocation - size in x8 register (encoding: 0xcb2863ff)
			{Assembly: "sub\tsp, sp, x8", Binary: wordToLineBinary(0xcb2863ff)},
			// Some work
			{Assembly: "mov\tx0, sp", Binary: wordToLineBinary(0x910003e0)},
			{Assembly: "bl\tsome_func", Binary: wordToLineBinary(0x94000000)},
			// Epilogue
			{Assembly: "ldp\tx29, x30, [sp, #16]", Binary: wordToLineBinary(0xa9417bfd)},
			{Assembly: "add\tsp, sp, #32", Binary: wordToLineBinary(0x910083ff)},
			{Assembly: "ret", Disassembled: "RET", Binary: wordToLineBinary(0xd65f03c0)},
		},
	}

	assert.PanicsWithValue(t,
		"dynamic_alloc_func: dynamic stack allocation detected (sub sp, sp, x8) - "+
			"alloca() and VLAs are not supported because Go requires stack size at compile time",
		func() {
			checkStackArm64(config.ARM64(), testFn)
		},
		"dynamic stack allocation should panic with clear error message")
}
