//go:build !noasm && arm64

// Code generated by gocc -- DO NOT EDIT.

package simd

import (
	"unsafe"

	"golang.org/x/sys/cpu"
)

var useSVE = cpu.ARM64.HasSVE

func uint8_simd_mul(input1 unsafe.Pointer, input2 unsafe.Pointer, output unsafe.Pointer, size uint64) {
	if useSVE {
		uint8_simd_mul_sve(input1, input2, output, size)
		return
	}
	uint8_simd_mul_neon(input1, input2, output, size)
}

// just to make compiling tests easier
func uint8_simd_mul_avx2(input1 unsafe.Pointer, input2 unsafe.Pointer, output unsafe.Pointer, size uint64) {
	panic("not implemented")
}

func uint8_simd_mul_avx512(input1 unsafe.Pointer, input2 unsafe.Pointer, output unsafe.Pointer, size uint64) {
	panic("not implemented")
}

func uint8_simd_mul_sse(input1 unsafe.Pointer, input2 unsafe.Pointer, output unsafe.Pointer, size uint64) {
	panic("not implemented")
}
