//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package simd

import "unsafe"

//go:noescape
func uint8_simd_mul(input1 unsafe.Pointer, input2 unsafe.Pointer, output unsafe.Pointer, size uint64)
