//go:build !noasm && arm64
// Code generated by gocc devel -- DO NOT EDIT.
//
// Source file         : test_simd_mul_sve.c
// Clang version       : Apple clang version 16.0.0 (clang-1600.0.26.4)
// Target architecture : arm64
// Compiler options    : -march=armv8.2-a+sve

#include "textflag.h"

TEXT ·uint8_simd_mul_sve_manual(SB), NOSPLIT, $0-32
	MOVD input1+0(FP), R0
	MOVD input2+8(FP), R1
	MOVD output+16(FP), R2
	MOVD size+24(FP), R3
	CBZ  R3, LBB0_4        // <--                                  // cbz	x3, .LBB0_4
	NOP                    // (skipped)                            // stp	x29, x30, [sp, #-16]!
	MOVD ZR, R8            // <--                                  // mov	x8, xzr
	WORD $0x04bf5029       // ?                                    // rdvl	x9, #1
	NOP                    // (skipped)                            // mov	x29, sp

LBB0_2:
	WORD $0x25231d00 // ?                                    // whilelo	p0.b, x8, x3
	WORD $0xa4084000 // ?                                    // ld1b	{ z0.b }, p0/z, [x0, x8]
	WORD $0xa4084021 // ?                                    // ld1b	{ z1.b }, p0/z, [x1, x8]
	WORD $0x04100020 // ?                                    // mul	z0.b, p0/m, z0.b, z1.b
	WORD $0xe4084040 // ?                                    // st1b	{ z0.b }, p0, [x2, x8]
	ADD  R9, R8, R8  // <--                                  // add	x8, x8, x9
	CMP  R3, R8      // <--                                  // cmp	x8, x3
	BCC  LBB0_2      // <--                                  // b.lo	.LBB0_2
	NOP              // (skipped)                            // ldp	x29, x30, [sp], #16

LBB0_4:
	RET // <--                                  // ret
